package com.infratrack.asset;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Permanent asset history event type (UC-011)")
public enum AssetHistoryEventType {
    ASSET_REGISTERED,
    BUSINESS_TRIGGER_CREATED,
    INSPECTION_ASSIGNED,
    INSPECTION_COMPLETED,
    ISSUE_RECORDED,
    OPERATIONAL_DECISION_MADE,
    WORK_ORDER_CREATED,
    WORK_ORDER_ASSIGNED,
    MAINTENANCE_COMPLETED,
    COMPLETION_REVIEW_RECORDED,
    REWORK_ISSUE_CREATED,
    SUGGESTED_ACTION_APPROVED,
    OPERATIONAL_DOCUMENT_UPLOADED,
    OPERATIONAL_DOCUMENT_DELETED
}
