package com.infratrack.asset;

public enum AssetHistoryEventType {
    ASSET_REGISTERED,
    BUSINESS_TRIGGER_CREATED,
    INSPECTION_ASSIGNED,
    INSPECTION_COMPLETED,
    ISSUE_RECORDED,
    OPERATIONAL_DECISION_MADE,
    WORK_ORDER_CREATED,
    WORK_ORDER_ASSIGNED,
    MAINTENANCE_COMPLETED,
    COMPLETION_REVIEW_RECORDED
}
