export const ASSET_HISTORY_EVENT_TYPES = {
  ASSET_REGISTERED: 'ASSET_REGISTERED',
  BUSINESS_TRIGGER_CREATED: 'BUSINESS_TRIGGER_CREATED',
  INSPECTION_ASSIGNED: 'INSPECTION_ASSIGNED',
  INSPECTION_COMPLETED: 'INSPECTION_COMPLETED',
  ISSUE_RECORDED: 'ISSUE_RECORDED',
  OPERATIONAL_DECISION_MADE: 'OPERATIONAL_DECISION_MADE',
  WORK_ORDER_CREATED: 'WORK_ORDER_CREATED',
  WORK_ORDER_ASSIGNED: 'WORK_ORDER_ASSIGNED',
  MAINTENANCE_COMPLETED: 'MAINTENANCE_COMPLETED',
  COMPLETION_REVIEW_RECORDED: 'COMPLETION_REVIEW_RECORDED',
  OPERATIONAL_DOCUMENT_UPLOADED: 'OPERATIONAL_DOCUMENT_UPLOADED',
  OPERATIONAL_DOCUMENT_DELETED: 'OPERATIONAL_DOCUMENT_DELETED',
};

const EVENT_TYPE_LABELS = {
  [ASSET_HISTORY_EVENT_TYPES.ASSET_REGISTERED]: 'Asset Registered',
  [ASSET_HISTORY_EVENT_TYPES.BUSINESS_TRIGGER_CREATED]: 'Business Trigger Created',
  [ASSET_HISTORY_EVENT_TYPES.INSPECTION_ASSIGNED]: 'Inspection Assigned',
  [ASSET_HISTORY_EVENT_TYPES.INSPECTION_COMPLETED]: 'Inspection Completed',
  [ASSET_HISTORY_EVENT_TYPES.ISSUE_RECORDED]: 'Issue Recorded',
  [ASSET_HISTORY_EVENT_TYPES.OPERATIONAL_DECISION_MADE]: 'Operational Decision Made',
  [ASSET_HISTORY_EVENT_TYPES.WORK_ORDER_CREATED]: 'Work Order Created',
  [ASSET_HISTORY_EVENT_TYPES.WORK_ORDER_ASSIGNED]: 'Work Order Assigned',
  [ASSET_HISTORY_EVENT_TYPES.MAINTENANCE_COMPLETED]: 'Maintenance Completed',
  [ASSET_HISTORY_EVENT_TYPES.COMPLETION_REVIEW_RECORDED]: 'Completion Review Recorded',
  [ASSET_HISTORY_EVENT_TYPES.OPERATIONAL_DOCUMENT_UPLOADED]: 'Operational Document Uploaded',
  [ASSET_HISTORY_EVENT_TYPES.OPERATIONAL_DOCUMENT_DELETED]: 'Operational Document Deleted',
};

export function getAssetHistoryEventTypeLabel(eventType) {
  return EVENT_TYPE_LABELS[eventType] || eventType;
}
