export const BUSINESS_TRIGGER_TYPES = {
  SCHEDULED_INSPECTION: 'SCHEDULED_INSPECTION',
  CUSTOMER_REQUEST: 'CUSTOMER_REQUEST',
  EMERGENCY_EVENT: 'EMERGENCY_EVENT',
  MANAGER_REQUEST: 'MANAGER_REQUEST',
  FIELD_OBSERVATION: 'FIELD_OBSERVATION',
};

export const BUSINESS_TRIGGER_TYPE_LABELS = {
  [BUSINESS_TRIGGER_TYPES.SCHEDULED_INSPECTION]: 'Scheduled Inspection',
  [BUSINESS_TRIGGER_TYPES.CUSTOMER_REQUEST]: 'Customer Request',
  [BUSINESS_TRIGGER_TYPES.EMERGENCY_EVENT]: 'Emergency Event',
  [BUSINESS_TRIGGER_TYPES.MANAGER_REQUEST]: 'Manager Request',
  [BUSINESS_TRIGGER_TYPES.FIELD_OBSERVATION]: 'Field Observation',
};

export const BUSINESS_TRIGGER_TYPE_OPTIONS = Object.entries(BUSINESS_TRIGGER_TYPE_LABELS).map(
  ([value, label]) => ({ value, label })
);

export function getBusinessTriggerTypeLabel(type) {
  return BUSINESS_TRIGGER_TYPE_LABELS[type] || type;
}
