import { DASHBOARD_TREND_RANGES } from './dashboardPreferences';

export const DASHBOARD = {
  DEFAULT_TREND_BUCKET: 'DAY',
  DEFAULT_ACTIVITY_LIMIT: 20,
  TREND_RANGE_DAYS: {
    [DASHBOARD_TREND_RANGES.LAST_7_DAYS]: 7,
    [DASHBOARD_TREND_RANGES.LAST_30_DAYS]: 30,
    [DASHBOARD_TREND_RANGES.LAST_90_DAYS]: 90,
  },
};

export function getDashboardTrendRangeDays(rangeKey) {
  return DASHBOARD.TREND_RANGE_DAYS[rangeKey]
    ?? DASHBOARD.TREND_RANGE_DAYS[DASHBOARD_TREND_RANGES.LAST_30_DAYS];
}
