export const DASHBOARD_WIDGET_TYPES = {
  OVERVIEW: 'OVERVIEW',
  ATTENTION: 'ATTENTION',
  TRENDS: 'TRENDS',
  RECENT_ACTIVITY: 'RECENT_ACTIVITY',
  QUICK_NAVIGATION: 'QUICK_NAVIGATION',
};

export const DEFAULT_WIDGET_ORDER = [
  DASHBOARD_WIDGET_TYPES.OVERVIEW,
  DASHBOARD_WIDGET_TYPES.ATTENTION,
  DASHBOARD_WIDGET_TYPES.TRENDS,
  DASHBOARD_WIDGET_TYPES.RECENT_ACTIVITY,
  DASHBOARD_WIDGET_TYPES.QUICK_NAVIGATION,
];

export const DASHBOARD_WIDGET_LABELS = {
  [DASHBOARD_WIDGET_TYPES.OVERVIEW]: 'KPI Overview',
  [DASHBOARD_WIDGET_TYPES.ATTENTION]: 'Attention Required',
  [DASHBOARD_WIDGET_TYPES.TRENDS]: 'Trends',
  [DASHBOARD_WIDGET_TYPES.RECENT_ACTIVITY]: 'Recent Activity',
  [DASHBOARD_WIDGET_TYPES.QUICK_NAVIGATION]: 'Quick Navigation',
};

export const DASHBOARD_TREND_RANGES = {
  LAST_7_DAYS: 'LAST_7_DAYS',
  LAST_30_DAYS: 'LAST_30_DAYS',
  LAST_90_DAYS: 'LAST_90_DAYS',
};

export const DASHBOARD_TREND_RANGE_LABELS = {
  [DASHBOARD_TREND_RANGES.LAST_7_DAYS]: 'Last 7 days',
  [DASHBOARD_TREND_RANGES.LAST_30_DAYS]: 'Last 30 days',
  [DASHBOARD_TREND_RANGES.LAST_90_DAYS]: 'Last 90 days',
};

export const DEFAULT_DASHBOARD_PREFERENCES = {
  showOverviewWidget: true,
  showAttentionWidget: true,
  showTrendWidget: true,
  showRecentActivityWidget: true,
  showQuickNavigationWidget: true,
  defaultTrendRange: DASHBOARD_TREND_RANGES.LAST_30_DAYS,
  widgetOrder: [...DEFAULT_WIDGET_ORDER],
};
