import {
  PASSWORD_MIN_LENGTH,
  PASSWORD_MAX_LENGTH,
} from './passwordPolicy';

export const FIELD_LIMITS = {
  PASSWORD_MIN_LENGTH,
  PASSWORD_MAX_LENGTH,
  INSPECTION_QUESTION_CODE_MAX_LENGTH: 100,
  API_ERROR_MESSAGE_MAX_LENGTH: 300,
  DEFAULT_DELEGATION_VALIDITY_DAYS: 7,
};

export const DISPLAY_LIMITS = {
  NOTIFICATION_BADGE_CAP: 99,
};
