export const OPERATIONAL_DECISION_OUTCOMES = {
  CONTINUE_MONITORING: 'CONTINUE_MONITORING',
  INTERNAL_MAINTENANCE: 'INTERNAL_MAINTENANCE',
  CONTRACTOR_WORK: 'CONTRACTOR_WORK',
  RENEWAL_RECOMMENDATION: 'RENEWAL_RECOMMENDATION',
  DECOMMISSION_RECOMMENDATION: 'DECOMMISSION_RECOMMENDATION',
};

export const OPERATIONAL_DECISION_OUTCOME_LABELS = {
  [OPERATIONAL_DECISION_OUTCOMES.CONTINUE_MONITORING]: 'Continue Monitoring',
  [OPERATIONAL_DECISION_OUTCOMES.INTERNAL_MAINTENANCE]: 'Internal Maintenance',
  [OPERATIONAL_DECISION_OUTCOMES.CONTRACTOR_WORK]: 'Contractor Work',
  [OPERATIONAL_DECISION_OUTCOMES.RENEWAL_RECOMMENDATION]: 'Renewal Recommendation',
  [OPERATIONAL_DECISION_OUTCOMES.DECOMMISSION_RECOMMENDATION]: 'Decommission Recommendation',
};

export const OPERATIONAL_DECISION_OUTCOME_OPTIONS = Object.entries(
  OPERATIONAL_DECISION_OUTCOME_LABELS
).map(([value, label]) => ({ value, label }));

export function getOperationalDecisionOutcomeLabel(outcome) {
  return OPERATIONAL_DECISION_OUTCOME_LABELS[outcome] || outcome;
}
