export const OPERATIONAL_DOCUMENT_TYPES = {
  PHOTO: 'PHOTO',
  REPORT: 'REPORT',
  MANUAL: 'MANUAL',
  PROCEDURE: 'PROCEDURE',
  QUOTATION: 'QUOTATION',
  DRAWING: 'DRAWING',
  OTHER: 'OTHER',
};

export const OPERATIONAL_DOCUMENT_OWNER_TYPES = {
  ASSET: 'ASSET',
  INSPECTION: 'INSPECTION',
  ISSUE: 'ISSUE',
  OPERATIONAL_DECISION: 'OPERATIONAL_DECISION',
  WORK_ORDER: 'WORK_ORDER',
  MAINTENANCE_ACTIVITY: 'MAINTENANCE_ACTIVITY',
  COMPLETION_REVIEW: 'COMPLETION_REVIEW',
};

const DOCUMENT_TYPE_LABELS = {
  [OPERATIONAL_DOCUMENT_TYPES.PHOTO]: 'Photo',
  [OPERATIONAL_DOCUMENT_TYPES.REPORT]: 'Report',
  [OPERATIONAL_DOCUMENT_TYPES.MANUAL]: 'Manual',
  [OPERATIONAL_DOCUMENT_TYPES.PROCEDURE]: 'Procedure',
  [OPERATIONAL_DOCUMENT_TYPES.QUOTATION]: 'Quotation',
  [OPERATIONAL_DOCUMENT_TYPES.DRAWING]: 'Drawing',
  [OPERATIONAL_DOCUMENT_TYPES.OTHER]: 'Other',
};

const OWNER_TYPE_LABELS = {
  [OPERATIONAL_DOCUMENT_OWNER_TYPES.ASSET]: 'Asset',
  [OPERATIONAL_DOCUMENT_OWNER_TYPES.INSPECTION]: 'Inspection',
  [OPERATIONAL_DOCUMENT_OWNER_TYPES.ISSUE]: 'Issue',
  [OPERATIONAL_DOCUMENT_OWNER_TYPES.OPERATIONAL_DECISION]: 'Operational Decision',
  [OPERATIONAL_DOCUMENT_OWNER_TYPES.WORK_ORDER]: 'Work Order',
  [OPERATIONAL_DOCUMENT_OWNER_TYPES.MAINTENANCE_ACTIVITY]: 'Maintenance Activity',
  [OPERATIONAL_DOCUMENT_OWNER_TYPES.COMPLETION_REVIEW]: 'Completion Review',
};

export const OPERATIONAL_DOCUMENT_TYPE_OPTIONS = Object.values(OPERATIONAL_DOCUMENT_TYPES).map(
  (value) => ({ value, label: DOCUMENT_TYPE_LABELS[value] })
);

export const OPERATIONAL_DOCUMENT_OWNER_TYPE_OPTIONS = Object.values(
  OPERATIONAL_DOCUMENT_OWNER_TYPES
).map((value) => ({ value, label: OWNER_TYPE_LABELS[value] }));

export function getOperationalDocumentTypeLabel(documentType) {
  return DOCUMENT_TYPE_LABELS[documentType] || documentType;
}

export function getOperationalDocumentOwnerTypeLabel(ownerType) {
  return OWNER_TYPE_LABELS[ownerType] || ownerType;
}
