export const PAGINATION = {
  DEFAULT_PAGE: 0,
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
};

export const DEFAULT_PAGE = PAGINATION.DEFAULT_PAGE;
export const DEFAULT_PAGE_SIZE = PAGINATION.DEFAULT_PAGE_SIZE;
export const DEFAULT_SIZE = PAGINATION.DEFAULT_PAGE_SIZE;
export const MAX_PAGE_SIZE = PAGINATION.MAX_PAGE_SIZE;
