export const PLAN_EVENT_TYPES = {
  COMPLETION_REVIEW: 'COMPLETION_REVIEW',
  INSPECTION_COMPLETED: 'INSPECTION_COMPLETED',
  WORK_ORDER_COMPLETED: 'WORK_ORDER_COMPLETED',
  MAINTENANCE_COMPLETED: 'MAINTENANCE_COMPLETED',
};

export const PLAN_EVENT_TYPE_LABELS = {
  [PLAN_EVENT_TYPES.COMPLETION_REVIEW]: 'Completion Review',
  [PLAN_EVENT_TYPES.INSPECTION_COMPLETED]: 'Inspection Completed',
  [PLAN_EVENT_TYPES.WORK_ORDER_COMPLETED]: 'Work Order Completed',
  [PLAN_EVENT_TYPES.MAINTENANCE_COMPLETED]: 'Maintenance Completed',
};

export const PLAN_EVENT_TYPE_OPTIONS = Object.entries(PLAN_EVENT_TYPE_LABELS).map(
  ([value, label]) => ({ value, label })
);
