export const PREVENTIVE_MAINTENANCE_PLAN_STATUSES = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  ARCHIVED: 'ARCHIVED',
};

export const PREVENTIVE_MAINTENANCE_PLAN_STATUS_LABELS = {
  [PREVENTIVE_MAINTENANCE_PLAN_STATUSES.DRAFT]: 'Draft',
  [PREVENTIVE_MAINTENANCE_PLAN_STATUSES.ACTIVE]: 'Active',
  [PREVENTIVE_MAINTENANCE_PLAN_STATUSES.PAUSED]: 'Paused',
  [PREVENTIVE_MAINTENANCE_PLAN_STATUSES.ARCHIVED]: 'Archived',
};

export const PREVENTIVE_MAINTENANCE_PLAN_STATUS_OPTIONS = Object.entries(
  PREVENTIVE_MAINTENANCE_PLAN_STATUS_LABELS
).map(([value, label]) => ({ value, label }));

export function getPreventiveMaintenancePlanStatusLabel(status) {
  return PREVENTIVE_MAINTENANCE_PLAN_STATUS_LABELS[status] || status;
}
