export const PREVENTIVE_MAINTENANCE_PLAN_PRIORITIES = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

export const PREVENTIVE_MAINTENANCE_PLAN_PRIORITY_LABELS = {
  [PREVENTIVE_MAINTENANCE_PLAN_PRIORITIES.LOW]: 'Low',
  [PREVENTIVE_MAINTENANCE_PLAN_PRIORITIES.MEDIUM]: 'Medium',
  [PREVENTIVE_MAINTENANCE_PLAN_PRIORITIES.HIGH]: 'High',
  [PREVENTIVE_MAINTENANCE_PLAN_PRIORITIES.CRITICAL]: 'Critical',
};

export const PREVENTIVE_MAINTENANCE_PLAN_PRIORITY_OPTIONS = Object.entries(
  PREVENTIVE_MAINTENANCE_PLAN_PRIORITY_LABELS
).map(([value, label]) => ({ value, label }));

export function getPreventiveMaintenancePlanPriorityLabel(priority) {
  return PREVENTIVE_MAINTENANCE_PLAN_PRIORITY_LABELS[priority] || priority;
}
