export { INSPECTION_STATUSES as INSPECTION_STATUS } from './inspectionPriorities';

export const WORK_ORDER_STATUS = {
  ASSIGNED: 'ASSIGNED',
  COMPLETED: 'COMPLETED',
};

export const SUGGESTED_ACTION_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  DISMISSED: 'DISMISSED',
};

export { EXECUTION_CANDIDATE_STATUS as PREVENTIVE_CANDIDATE_STATUS } from './executionCandidateStatuses';
