export const COMMON_LABELS = {
  LOADING: 'Loading...',
  SAVE: 'Save',
  CANCEL: 'Cancel',
  CLOSE: 'Close',
  EDIT: 'Edit',
  DELETE: 'Delete',
  CREATE: 'Create',
  EXPORT_CSV: 'Export CSV',
  EXPORT_XLSX: 'Export XLSX',
  EXPORT_PDF: 'Export PDF',
  EXPORTING: 'Exporting...',
  LOGOUT: 'Logout',
  BACK: '← Back',
};
