export const COMMON_LABELS = {
  LOADING: 'Loading...',
  SAVE: 'Save',
  CANCEL: 'Cancel',
  CLOSE: 'Close',
  EDIT: 'Edit',
  DELETE: 'Delete',
  CREATE: 'Create',
  EXPORT_CSV: 'Export CSV',
  EXPORT_XLSX: 'Export XLSX',
  EXPORT_PDF: 'Export PDF',
  EXPORT: 'Export',
  EXPORT_AS_CSV: 'Export as CSV',
  EXPORT_AS_XLSX: 'Export as XLSX',
  EXPORT_AS_PDF: 'Export as PDF',
  EXPORTING: 'Exporting...',
  EXPORT_RANGE: 'Export range:',
  EXPORT_FROM_DATE: 'Export from date',
  EXPORT_TO_DATE: 'Export to date',
  LOGOUT: 'Logout',
  BACK: '← Back',
};
